name: youtube_player_flutter
description: Flutter plugin for playing or streaming inline YouTube videos using the official iFrame player API. This plugin supports both Android and iOS.
version: 8.1.2
repository: https://github.com/sarbagyastha/youtube_player_flutter
homepage: https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_flutter

# environment:
#   sdk: '>=2.17.0 <3.0.0'
#   flutter: '>=3.0.0'

environment:
  sdk: ">=3.0.0-239.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_inappwebview: ^6.0.0-beta.24+1



  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview

dependency_overrides:
  # para compatibilidad de windows, separaron en(flutter_inappwebview_platform_interface) fijarse en: C:\mycode\flutter\clones\flutter_inappwebview\flutter_inappwebview\example
  flutter_inappwebview_platform_interface:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_platform_interface

  flutter_inappwebview_android:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_android

  flutter_inappwebview_ios:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios

  flutter_inappwebview_macos:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_macos

  flutter_inappwebview_web:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_web

  flutter_inappwebview_windows:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_windows


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/speedometer.webp
